server:
  port: 9013
# spring.cloud.config.discovery.enabled 是从配置中心读取文件。
# spring.cloud.config.discovery.serviceId 配置中心的servieId，即服务名。
spring:
  application:
    name: bc-app
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: false
        service-id: bc-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/


