server:
  port: 9013
# spring.cloud.config.discovery.enabled 是从配置中心读取文件。
# spring.cloud.config.discovery.serviceId 配置中心的servieId，即服务名。
spring:
  application:
    name: bc-app
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: false
        service-id: bc-config
  datasource:
    url: jdbc:mysql://localhost/app?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

mybatis:
  type-aliases-package: exercise.bc.app.*.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*/*.xml

