server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

# spring.cloud.config.server.git.uri：配置git仓库地址
# spring.cloud.config.server.git.searchPaths：配置仓库路径
# spring.cloud.config.label：配置仓库的分支
# spring.cloud.config.server.git.username：访问git仓库的用户名
# spring.cloud.config.server.git.password：访问git仓库的用户密码
spring:
  application:
    name: bc-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
          default-label: master
          username: your username
          password: your password