server:
  port: 9009

spring:
  application:
    name: bc-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    api-one:
      path: /api-one/**
      serviceId: bc-web

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000