server:
  port: 9009

spring:
  application:
    name: bc-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

zuul:
  routes:
    api-one:
      path: /api-one/**
      serviceId: bc-web