server:
  port: 8888
# spring.cloud.config.discovery.enabled 是从配置中心读取文件。
# spring.cloud.config.discovery.serviceId 配置中心的servieId，即服务名。
spring:
  application:
    name: bc-wechat-mp

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/